#!/bin/bash
# Quick Setup & Testing Guide for User Import Feature

echo "╔════════════════════════════════════════════════════════╗"
echo "║  User Import from Excel - Quick Setup Guide           ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

echo "📋 Step 1: Create Sample Excel File"
echo "Command: node scripts/createSampleExcel.js"
echo ""

echo "📧 Step 2: Configure Mailtrap"
echo "File: utils/sendMailHandler.js"
echo "Update: auth.user and auth.pass with your Mailtrap credentials"
echo "Get credentials: https://mailtrap.io → Inbox → Integrations → NodeJS"
echo ""

echo "🚀 Step 3: Start Server"
echo "Command: npm start"
echo ""

echo "🧪 Step 4: Test API with Postman or Curl"
echo ""
echo "POSTMAN:"
echo "  Method: POST"
echo "  URL: http://localhost:3000/api/v1/import/import-users"
echo "  Headers:"
echo "    - Authorization: Bearer YOUR_ADMIN_TOKEN"
echo "    - Content-Type: application/json"
echo ""
echo "CURL:"
echo "  curl -X POST http://localhost:3000/api/v1/import/import-users \\"
echo "    -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "    -H 'Content-Type: application/json'"
echo ""

echo "📧 Step 5: Check Mailtrap"
echo "  1. Go to https://mailtrap.io"
echo "  2. Click on your Inbox"
echo "  3. You should see 5 emails with user credentials"
echo ""

echo "✅ Expected Results:"
echo "  - 5 new users in MongoDB"
echo "  - 5 emails received in Mailtrap"
echo "  - Each email contains username and 16-char random password"
echo ""

echo "📄 Documentation:"
echo "  1. IMPORT_USERS_GUIDE.md - Full Vietnamese guide"
echo "  2. IMPLEMENTATION_SUMMARY.md - Technical summary"
echo ""

echo "🔍 Files Changed:"
echo "  NEW:"
echo "    ✓ controllers/importUsers.js"
echo "    ✓ routes/importUsers.js"
echo "    ✓ scripts/createSampleExcel.js"
echo "    ✓ uploads/user.xlsx"
echo ""
echo "  UPDATED:"
echo "    ✓ utils/sendMailHandler.js (added sendMailPassword function)"
echo "    ✓ app.js (added import route)"
echo ""

echo "🔗 API Endpoint:"
echo "  POST /api/v1/import/import-users"
echo "  Role Required: ADMIN"
echo "  Authentication: Required (Bearer Token)"
echo ""

echo "🐛 Troubleshooting:"
echo "  File not found → Run: node scripts/createSampleExcel.js"
echo "  Role not found → Create 'user' role in database first"
echo "  Email not sent → Check Mailtrap credentials in sendMailHandler.js"
echo "  Unauthorized → Use ADMIN token"
echo ""

echo "🎯 Quick Commands:"
echo "  npm start                           # Start server"
echo "  node scripts/createSampleExcel.js   # Generate Excel file"
echo "  git status                          # Check git status"
echo "  git log --oneline                   # Show git history"
echo ""

echo "✅ Done! Follow steps 1-5 above to test the feature."
